
package com.ranuka.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldImpl", targetNamespace = "http://webService.ranuka.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://webService.ranuka.com/", className = "com.ranuka.webservice.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://webService.ranuka.com/", className = "com.ranuka.webservice.HelloWorldResponse")
    @Action(input = "http://webService.ranuka.com/HelloWorldImpl/HelloWorldRequest", output = "http://webService.ranuka.com/HelloWorldImpl/HelloWorldResponse")
    public String helloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
